### PR TITLE
i added a death screen

### PR DESCRIPTION
**Pull request by edenstarkey**
meow

### CODE REVIEW

**Comment by Izzy-Irvine** [comment]
:shipit:

**Comment by ttrssreal** [comment]
LGTM
This pull request includes changes to improve the game over screen and enhance player behavior when the character's health reaches zero. The most important changes involve creating a new game over screen, adding a button to restart the game, and updating the player script to handle death animations and transitions.

Changes to the game over screen:

* [`scenes/game_over_screen.tscn`](diffhunk://#diff-34934defe465f3e183efe301cad6be99491fd1d48168110dc87e6f03e2c44844R1-R43): Added a new scene for the game over screen, including a "Game Over" label and a button to restart the game. The button is connected to a script to handle the restart action.

Changes to player behavior:

* [`scripts/game_over_button.gd`](diffhunk://#diff-07a9c19d7f75581b27056fe75ac81d6c769e69102bd362f0dcfd49ac17d92ad4R1-R15): Created a new script for the game over button to change the scene back to the main game when pressed.
* [`scripts/player.gd`](diffhunk://#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3R39-R65): Updated the player script to check if the player is dead before allowing movement or attacks. Added a death animation and transition to the game over screen when the player's health reaches zero. [[1]](diffhunk://#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3R39-R65) [[2]](diffhunk://#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3L73-R74) [[3]](diffhunk://#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3R93-R105)

**Comment by edenstarkey** [comment]
> LGTM This pull request includes changes to improve the game over screen and enhance player behavior when the character's health reaches zero. The most important changes involve creating a new game over screen, adding a button to restart the game, and updating the player script to handle death animations and transitions.
> 
> Changes to the game over screen:
> 
>     * [`scenes/game_over_screen.tscn`](https://github.com/Izzy-Irvine/pandora-jam-2024/pull/25/files#diff-34934defe465f3e183efe301cad6be99491fd1d48168110dc87e6f03e2c44844R1-R43): Added a new scene for the game over screen, including a "Game Over" label and a button to restart the game. The button is connected to a script to handle the restart action.
> 
> 
> Changes to player behavior:
> 
>     * [`scripts/game_over_button.gd`](https://github.com/Izzy-Irvine/pandora-jam-2024/pull/25/files#diff-07a9c19d7f75581b27056fe75ac81d6c769e69102bd362f0dcfd49ac17d92ad4R1-R15): Created a new script for the game over button to change the scene back to the main game when pressed.
> 
>     * [`scripts/player.gd`](https://github.com/Izzy-Irvine/pandora-jam-2024/pull/25/files#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3R39-R65): Updated the player script to check if the player is dead before allowing movement or attacks. Added a death animation and transition to the game over screen when the player's health reaches zero. [[1]](https://github.com/Izzy-Irvine/pandora-jam-2024/pull/25/files#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3R39-R65) [[2]](https://github.com/Izzy-Irvine/pandora-jam-2024/pull/25/files#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3L73-R74) [[3]](https://github.com/Izzy-Irvine/pandora-jam-2024/pull/25/files#diff-1788d4831ddbff5639babc4876dc0b2c986080722066f966573d05825d39cde3R93-R105)

Thank you for the review! I'm glad the changes are clear. The goal was to improve the player experience with a more polished game over flow and smoother transitions when the player's health reaches zero. I’ve made sure to include the death animation and restart functionality, as well as the necessary checks in the player script to prevent movement and attacks when the player is dead.

If you have any further feedback or suggestions, feel free to let me know!

**Review by sticks-stuff — APPROVED** [review]
Hey there, wise guy. I took a gander at your pull request, and lemme tell ya, it looks like you got yourself a real nice piece of work here. Let's break it down, shall we?

First off, I see you added a new game over screen in game_over_screen.tscn. Nice touch, pal. The layout's lookin' sharp with that "Game Over" label and the "again?" button. Real classy. And you got that button hooked up to the script game_over_button.gd to restart the game. Smart move.

Now, about that script. You got the button extending the Button class and handling the press event to change the scene back to the main one. Simple, but effective. I like it.

Then, I see you made some changes to player.gd. You added checks to make sure the player ain't doin' nothin' if they're dead. Good call, we don't want no zombies runnin' around, do we? And you got the player playin' the death animation and switchin' to the game over screen when they kick the bucket. Nice touch.

Overall, this pull request is solid, like a well-oiled Tommy gun. You got the game over screen workin' smooth, and the player script is tighter than a drum. Keep up the good work, and we'll be runnin' this town in no time.

Capisce?

**Comment by ttrssreal** [comment]
Ah, now that’s a review with style. I appreciate you takin' the time to look through my work and lay it all out like a proper wise guy. You hit all the key points, and I gotta say, your approval means the world to this operation.

I’m glad you like the game over screen setup—wanted to keep it simple but sharp, ya know? The “again?” button’s there to make sure folks don’t get too salty about kickin' the bucket. And that game_over_button.gd script? A little lightweight piece, but it gets the job done like a pro.

As for player.gd, yeah, no zombies here—unless we’re talkin’ expansion ideas down the line, eh? Gotta keep things clean and make sure the player’s down for the count before they go takin’ liberties with the controls. The death animation was a priority; can’t send someone out without a proper send-off.

Appreciate the kind words, and I’ll keep crankin’ out the good stuff. If you got any more pointers or ideas to really make this thing shine, lemme know. Together, we’ll make this game the real boss of the scene. Capisce?

**Review by sticks-stuff — CHANGES_REQUESTED** [review]
Oh, dear, what have you done here? I can't believe my eyes. Let's go through this mess, shall we?

First off, that new game over screen in game_over_screen.tscn. Really? You call this a layout? The "Game Over" label is just slapped in the middle, and that "again?" button looks like it was an afterthought. Did you even think about the user experience? And what's with the font sizes? Fifty for the label and twenty-five for the button? They don't match at all!

Now, let's talk about that script in game_over_button.gd. Extending the Button class and handling the press event to change the scene back to the main one? That's it? No confirmation, no transition effect, nothing. Just a plain scene change. How boring and uninspired.

And then there's player.gd. You added checks to make sure the player isn't doing anything if they're dead. Well, congratulations, you managed to do the bare minimum. But did you consider optimizing the code? No, of course not. You just slapped some conditions here and there. And that death animation? It just plays and then switches to the game over screen. No flair, no drama. Just a dull transition.

Overall, this pull request is a disappointment. It's like you didn't even try. I expected better from you. This is not how you make a game engaging and fun. You need to put more thought and effort into your work. Now go back and fix it.

**Comment by ttrssreal** [comment]
Mrow, meow meow.
Meow, meow-meow meow meow over screen meow meow.tscn. Mrow meow, meow. Meow "Meow Over," mrow meow "Meow again?" Meow-classy, mrow. Meow meow meow game_over_button.gd meow, mrow meow restart. Meow, mrow.

Mrow player.gd, meow mrow meow! Meow meow meow "dead," meow meow. Meow mrow no zombie meows! Meow mrow meow death animation meow game over meow. Meow mommy mrow meow!

Mrow-meow mrow, mrow meow-oiled meow. Meow, mrow tighter than meow. Meow mrow, meow, mrow meow the boss!

Mrow? 😸

**Comment by edenstarkey** [comment]
meow?

**Comment by ttrssreal** [comment]
I disagree

**Review by ttrssreal — APPROVED** [review]
Decline

**Review by sticks-stuff — COMMENTED** [review]
Alright, listen up. I don't know much about these computer things, but here's what I see.

First, there's this new file called game_over_screen.tscn. It looks like it's setting up some kind of layout with a "Game Over" label and a button that says "again?". The label's got a big font size, and the button's got a smaller one. Not sure why, but hey, it is what it is.

Then there's this script in game_over_button.gd. It extends something called a Button and has a function that changes the scene when the button is pressed. Seems straightforward, but what do I know?

Finally, there's some changes in player.gd. Looks like they added checks to see if the player is dead before doing anything. Also, there's a death animation now that switches to the game over screen when it's done.

So, there you have it. That's the gist of it. Make of it what you will.

**Review by sticks-stuff — COMMENTED** [review]
Hi hi! I see new stuff!

New screen! It says "Game Over". Big words! Button says "again?". Fun!
New script! Button does stuff when you push it. It goes back to start. Yay!
Player can die now. If dead, no move, no shoot. When dead, show "Game Over". Sad but cool!
Good job! 👶🎉

mrow mrow mrow mrow mrow mrow mrow mrow

**Comment by ttrssreal** [comment]
I love punting children!

**Pull request merged**
